// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	goqu "github.com/doug-martin/goqu/v9"

	mock "github.com/stretchr/testify/mock"
)

// DBService is an autogenerated mock type for the DBService type
type DBService struct {
	mock.Mock
}

type DBService_Expecter struct {
	mock *mock.Mock
}

func (_m *DBService) EXPECT() *DBService_Expecter {
	return &DBService_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function with given fields: ctx
func (_m *DBService) Begin(ctx context.Context) (context.Context, error) {
	ret := _m.Called(ctx)

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (context.Context, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) context.Context); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DBService_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type DBService_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DBService_Expecter) Begin(ctx interface{}) *DBService_Begin_Call {
	return &DBService_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *DBService_Begin_Call) Run(run func(ctx context.Context)) *DBService_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *DBService_Begin_Call) Return(_a0 context.Context, _a1 error) *DBService_Begin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DBService_Begin_Call) RunAndReturn(run func(context.Context) (context.Context, error)) *DBService_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function with given fields: ctx
func (_m *DBService) Commit(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DBService_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type DBService_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DBService_Expecter) Commit(ctx interface{}) *DBService_Commit_Call {
	return &DBService_Commit_Call{Call: _e.mock.On("Commit", ctx)}
}

func (_c *DBService_Commit_Call) Run(run func(ctx context.Context)) *DBService_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *DBService_Commit_Call) Return(_a0 error) *DBService_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DBService_Commit_Call) RunAndReturn(run func(context.Context) error) *DBService_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function with given fields: ctx, sql, args
func (_m *DBService) Count(ctx context.Context, sql string, args []interface{}) (int64, error) {
	ret := _m.Called(ctx, sql, args)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []interface{}) (int64, error)); ok {
		return rf(ctx, sql, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []interface{}) int64); ok {
		r0 = rf(ctx, sql, args)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []interface{}) error); ok {
		r1 = rf(ctx, sql, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DBService_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type DBService_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args []interface{}
func (_e *DBService_Expecter) Count(ctx interface{}, sql interface{}, args interface{}) *DBService_Count_Call {
	return &DBService_Count_Call{Call: _e.mock.On("Count", ctx, sql, args)}
}

func (_c *DBService_Count_Call) Run(run func(ctx context.Context, sql string, args []interface{})) *DBService_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]interface{}))
	})
	return _c
}

func (_c *DBService_Count_Call) Return(_a0 int64, _a1 error) *DBService_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DBService_Count_Call) RunAndReturn(run func(context.Context, string, []interface{}) (int64, error)) *DBService_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Dialect provides a mock function with given fields:
func (_m *DBService) Dialect() goqu.DialectWrapper {
	ret := _m.Called()

	var r0 goqu.DialectWrapper
	if rf, ok := ret.Get(0).(func() goqu.DialectWrapper); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(goqu.DialectWrapper)
	}

	return r0
}

// DBService_Dialect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dialect'
type DBService_Dialect_Call struct {
	*mock.Call
}

// Dialect is a helper method to define mock.On call
func (_e *DBService_Expecter) Dialect() *DBService_Dialect_Call {
	return &DBService_Dialect_Call{Call: _e.mock.On("Dialect")}
}

func (_c *DBService_Dialect_Call) Run(run func()) *DBService_Dialect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DBService_Dialect_Call) Return(_a0 goqu.DialectWrapper) *DBService_Dialect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DBService_Dialect_Call) RunAndReturn(run func() goqu.DialectWrapper) *DBService_Dialect_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function with given fields: ctx, query, args
func (_m *DBService) Exec(ctx context.Context, query string, args []interface{}) error {
	ret := _m.Called(ctx, query, args)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []interface{}) error); ok {
		r0 = rf(ctx, query, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DBService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type DBService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args []interface{}
func (_e *DBService_Expecter) Exec(ctx interface{}, query interface{}, args interface{}) *DBService_Exec_Call {
	return &DBService_Exec_Call{Call: _e.mock.On("Exec", ctx, query, args)}
}

func (_c *DBService_Exec_Call) Run(run func(ctx context.Context, query string, args []interface{})) *DBService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]interface{}))
	})
	return _c
}

func (_c *DBService_Exec_Call) Return(_a0 error) *DBService_Exec_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DBService_Exec_Call) RunAndReturn(run func(context.Context, string, []interface{}) error) *DBService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: ctx, sql, args, dest
func (_m *DBService) Insert(ctx context.Context, sql string, args []interface{}, dest interface{}) error {
	ret := _m.Called(ctx, sql, args, dest)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []interface{}, interface{}) error); ok {
		r0 = rf(ctx, sql, args, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DBService_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type DBService_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args []interface{}
//   - dest interface{}
func (_e *DBService_Expecter) Insert(ctx interface{}, sql interface{}, args interface{}, dest interface{}) *DBService_Insert_Call {
	return &DBService_Insert_Call{Call: _e.mock.On("Insert", ctx, sql, args, dest)}
}

func (_c *DBService_Insert_Call) Run(run func(ctx context.Context, sql string, args []interface{}, dest interface{})) *DBService_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]interface{}), args[3].(interface{}))
	})
	return _c
}

func (_c *DBService_Insert_Call) Return(_a0 error) *DBService_Insert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DBService_Insert_Call) RunAndReturn(run func(context.Context, string, []interface{}, interface{}) error) *DBService_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// InsertMany provides a mock function with given fields: ctx, sql, args, dest
func (_m *DBService) InsertMany(ctx context.Context, sql string, args []interface{}, dest interface{}) error {
	ret := _m.Called(ctx, sql, args, dest)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []interface{}, interface{}) error); ok {
		r0 = rf(ctx, sql, args, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DBService_InsertMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMany'
type DBService_InsertMany_Call struct {
	*mock.Call
}

// InsertMany is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args []interface{}
//   - dest interface{}
func (_e *DBService_Expecter) InsertMany(ctx interface{}, sql interface{}, args interface{}, dest interface{}) *DBService_InsertMany_Call {
	return &DBService_InsertMany_Call{Call: _e.mock.On("InsertMany", ctx, sql, args, dest)}
}

func (_c *DBService_InsertMany_Call) Run(run func(ctx context.Context, sql string, args []interface{}, dest interface{})) *DBService_InsertMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]interface{}), args[3].(interface{}))
	})
	return _c
}

func (_c *DBService_InsertMany_Call) Return(_a0 error) *DBService_InsertMany_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DBService_InsertMany_Call) RunAndReturn(run func(context.Context, string, []interface{}, interface{}) error) *DBService_InsertMany_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields: ctx
func (_m *DBService) Rollback(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DBService_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type DBService_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DBService_Expecter) Rollback(ctx interface{}) *DBService_Rollback_Call {
	return &DBService_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *DBService_Rollback_Call) Run(run func(ctx context.Context)) *DBService_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *DBService_Rollback_Call) Return(_a0 error) *DBService_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DBService_Rollback_Call) RunAndReturn(run func(context.Context) error) *DBService_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// Select provides a mock function with given fields: ctx, sql, args, dest, relations
func (_m *DBService) Select(ctx context.Context, sql string, args []interface{}, dest interface{}, relations ...string) error {
	_va := make([]interface{}, len(relations))
	for _i := range relations {
		_va[_i] = relations[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, sql, args, dest)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []interface{}, interface{}, ...string) error); ok {
		r0 = rf(ctx, sql, args, dest, relations...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DBService_Select_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Select'
type DBService_Select_Call struct {
	*mock.Call
}

// Select is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args []interface{}
//   - dest interface{}
//   - relations ...string
func (_e *DBService_Expecter) Select(ctx interface{}, sql interface{}, args interface{}, dest interface{}, relations ...interface{}) *DBService_Select_Call {
	return &DBService_Select_Call{Call: _e.mock.On("Select",
		append([]interface{}{ctx, sql, args, dest}, relations...)...)}
}

func (_c *DBService_Select_Call) Run(run func(ctx context.Context, sql string, args []interface{}, dest interface{}, relations ...string)) *DBService_Select_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].([]interface{}), args[3].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *DBService_Select_Call) Return(_a0 error) *DBService_Select_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DBService_Select_Call) RunAndReturn(run func(context.Context, string, []interface{}, interface{}, ...string) error) *DBService_Select_Call {
	_c.Call.Return(run)
	return _c
}

// SelectOne provides a mock function with given fields: ctx, sql, args, dest, relations
func (_m *DBService) SelectOne(ctx context.Context, sql string, args []interface{}, dest interface{}, relations ...string) error {
	_va := make([]interface{}, len(relations))
	for _i := range relations {
		_va[_i] = relations[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, sql, args, dest)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []interface{}, interface{}, ...string) error); ok {
		r0 = rf(ctx, sql, args, dest, relations...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DBService_SelectOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectOne'
type DBService_SelectOne_Call struct {
	*mock.Call
}

// SelectOne is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args []interface{}
//   - dest interface{}
//   - relations ...string
func (_e *DBService_Expecter) SelectOne(ctx interface{}, sql interface{}, args interface{}, dest interface{}, relations ...interface{}) *DBService_SelectOne_Call {
	return &DBService_SelectOne_Call{Call: _e.mock.On("SelectOne",
		append([]interface{}{ctx, sql, args, dest}, relations...)...)}
}

func (_c *DBService_SelectOne_Call) Run(run func(ctx context.Context, sql string, args []interface{}, dest interface{}, relations ...string)) *DBService_SelectOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].([]interface{}), args[3].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *DBService_SelectOne_Call) Return(_a0 error) *DBService_SelectOne_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DBService_SelectOne_Call) RunAndReturn(run func(context.Context, string, []interface{}, interface{}, ...string) error) *DBService_SelectOne_Call {
	_c.Call.Return(run)
	return _c
}

// NewDBService creates a new instance of DBService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDBService(t interface {
	mock.TestingT
	Cleanup(func())
}) *DBService {
	mock := &DBService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
